//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int IdColorP { get; set; }
        public string ColorName { get; set; }
    
        public virtual ICollection<Point> Points { get; set; }
    }
}
