//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Points = new HashSet<Point>();
            this.SavePoints1 = new HashSet<SavePoint>();
        }
    
        public int IdField { get; set; }
        public int IdSavePoint { get; set; }
    
        public virtual SavePoint SavePoints { get; set; }
        public virtual ICollection<Point> Points { get; set; }
        public virtual ICollection<SavePoint> SavePoints1 { get; set; }
    }
}
