//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FigurType
    {
        public FigurType()
        {
            this.Figures = new HashSet<Figure>();
        }
    
        public int IdFigureType { get; set; }
        public string FigName { get; set; }
    
        public virtual ICollection<Figure> Figures { get; set; }
    }
}
