//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Figure
    {
        public Figure()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int IdFig { get; set; }
        public Nullable<int> IdFigureType { get; set; }
        public int IdSavePoint { get; set; }
        public bool CurrentFig { get; set; }
    
        public virtual FigurType FigurTypes { get; set; }
        public virtual SavePoint SavePoints { get; set; }
        public virtual ICollection<Point> Points { get; set; }
    }
}
