//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public long IdPoint { get; set; }
        public Nullable<int> IdField { get; set; }
        public Nullable<int> IdFig { get; set; }
        public int IdColorP { get; set; }
        public byte X { get; set; }
        public byte Y { get; set; }
    
        public virtual Color Colors { get; set; }
        public virtual Field Fields { get; set; }
        public virtual Figure Figures { get; set; }
    }
}
