//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavePoint
    {
        public SavePoint()
        {
            this.Fields = new HashSet<Field>();
            this.Figures = new HashSet<Figure>();
        }
    
        public int IdSavePoint { get; set; }
        public Nullable<int> IdField { get; set; }
        public System.DateTime Date { get; set; }
        public int Level { get; set; }
        public int BurnedLine { get; set; }
        public int Score { get; set; }
    
        public virtual ICollection<Field> Fields { get; set; }
        public virtual Field Fields1 { get; set; }
        public virtual ICollection<Figure> Figures { get; set; }
    }
}
