//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TetrisDataContext : DbContext
    {
        public TetrisDataContext()
            : base("name=TetrisDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Figure> Figures { get; set; }
        public virtual DbSet<FigurType> FigurTypes { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<SavePoint> SavePoints { get; set; }
    }
}
